version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "daily"
    default_labels:
      - "govuk-pay"
      - "dependencies"
  - package_manager: "docker"
    directory: "/"
    update_schedule: "weekly"
    default_labels:
      - "govuk-pay"
      - "dependencies"
